### ISSUE TITLE
ConfigPath : if wrong no error is raised

### ISSUE THREAD

**Issue by soleil-ica** [esrf-bliss/Lima-camera-maxipix#1]
If the config path doesn't exist, no error is thrown, then the plugin seems OK, but in fact it is not as the config is not loaded

**Comment by laurent-claustre** [comment]
I found the problem, it comes from the tools file MpxCommon.cpp and checkPath() function which throws an exception LIMA_EXEC, but the exception is ignored !!!!
I'm investigating....

**Comment by laurent-claustre** [comment]
The issue is now fixed,
