### ISSUE TITLE
ManualShutterState: not supported, then throw error infinitely

### ISSUE THREAD

**Issue by soleil-ica** [esrf-bliss/Lima-camera-maxipix#2]
think of a way to support the fact that the Maxipix does not support ManualShutter

**Comment by laurent-claustre** [comment]
ShutterCtrlObj::getState() should not be called by client if the mode ShutterManual is not supported.
Client must check supported mode by calling ShutterCtrlObj:checkMode(ShutterManual),
if false is return, this mode is not supported otherwise it is supported.

**Comment by laurent-claustre** [comment]
You can also pick up the list of supported modes with getModeList()
